#!/bin/bash

cd grammar
# this is antlr4
java -jar /usr/local/lib/antlr-4.7-complete.jar atalk.g4 && \
# this compiles java files generated by antlr 
javac atalk*.java && \
# this is grun
java org.antlr.v4.gui.TestRig atalk program -gui < $1 > ../tests/output

rm *.class
rm *.tokens
rm atalk*.java