#!/bin/bash

# # this is antlr4
# java -jar /usr/local/lib/antlr-4.7-complete.jar AtalkPass1.g4 && \
# java -jar /usr/local/lib/antlr-4.7-complete.jar AtalkPass2.g4 && \
# # this compiles java files generated by antlr 
# javac *.java && \
# # this is grun
# java org.antlr.v4.gui.TestRig atalk program < $1 > output

# rm *.class
# rm *.tokens
# rm atalk*.java
# #rm Atalk*.java
export CLASSPATH=".:/usr/local/lib/antlr-4.7-complete.jar:$CLASSPATH"
rm *.class
rm *.tokens
rm AtalkPass1*.java
rm AtalkPass2*.java
java -jar /usr/local/lib/antlr-4.7-complete.jar AtalkPass1.g4
java -jar /usr/local/lib/antlr-4.7-complete.jar AtalkPass2.g4
javac *.java
java Atalk $1
# java < $1 > output